## 01. numpy

--다차원 배열을 쉽고 효율적으로 사용할 수 있도록 지원하는 파이썬 라이브러리
- 데이터 분석 라이브러리에 많이 사용됨.

### 1-1. ndarray
- numpy의 핵심 데이터 구조
- 동일한 자료형의 다차원 배열


In [3]:
import numpy as np

In [4]:
# ndarry의 생성 
# 쉬프트 + 엔터: 실행

a = np.array([[1,2,3],[4,5,6]])
b = np.array([1.0,3.14,1,24])

a

# 배열의 구조
print(f"배열의 구조: {a.shape}")

# 배열의 차원 수
print(f"배열의 차원: {a.ndim}")

#데이터 타입
print(f"배열의 데이터 타입: {a.dtype}")
print(f"배열의 데이터 타입: {b.dtype}")

#형변환
new_a = a.astype(np.float64)
print(f"수정한 배열의 데이터 타입: {new_a.dtype}")



배열의 구조: (2, 3)
배열의 차원: 2
배열의 데이터 타입: int64
배열의 데이터 타입: float64
수정한 배열의 데이터 타입: float64


In [14]:
# 3차원 행렬
a = np.array([[[1,2,3],[4,5,6]],
              [[1,2,3],[4,5,6]],
              [[1,2,3],[4,5,6]]])

print(f"배열의 구조: {a.shape}")
print(f"배열의 차원: {a.ndim}")

배열의 구조: (3, 2, 3)
배열의 차원: 3


### 1-2. 배열 초기화

In [11]:
# 모든 요소가 0인 배열 생성
np.zeros((3,4)) #2차원
np.zeros((2,3,4),dtype=np.int64) #3차원

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [12]:
#(원소의 값이) 초기화 되지 않은 배열 생성
np.empty((2,3))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [8.45596650e-307, 1.89146896e-307, 7.56571288e-307]])

In [15]:
# 주어진 값으로 채운 배열
np.full((3,3), 7)


array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [17]:
# 단위 행렬
np.eye(3, 3)
np.eye(3,5,-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

### 1-3 범위 기반 배열 생성

In [18]:
# arange : range()와 유사한 기능 제공
# 시작 이상 끝 미만의 정수 배열을 지정한 간격으로 생성
np.arange(0, 10)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
# linspace : 시작~ 끝까지 균일 간격으로 지정한 개수만큼 숫자를 생성
# 끝을 포함함

np.linspace(10,100,10)
np.linspace(0.1 ,1, 10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### 1-4. 랜덤 배열 생성

In [20]:
# random.rand(m,n) 0 ~ 1 사이의 난수로 초기화 
np.random.rand(2, 3)

array([[0.45434285, 0.7790241 , 0.7897597 ],
       [0.36614811, 0.48994762, 0.25849197]])

In [ ]:
# random.randn(m, n): 표준 정규분포를 따르는 난수로 초기화
#표준정규분포: 평균 0, 분산 1인 정규분포
np.random.randn(2, 4, 5)

#random.randint(low,high,(size))
np.random.randint(10, 20, (2,4))

array([[13, 13, 13, 10],
       [15, 19, 15, 14]], dtype=int32)

In [22]:
#random.seed() : 난수 생성시 시작값 제공

np.random.seed(42)
print(np.random.rand(2,3))

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]


In [24]:
#RNG(Random Number Generator) : 최근 Numpy 사용에서 권장되는 방식

from numpy.random import default_rng

rng = default_rng(seed=2)
rng2 = default_rng(seed = 10)

print(rng.random((3,2)))
print(rng2.random((4,4)))

[[0.26161213 0.29849114]
 [0.81422574 0.09191594]
 [0.60010053 0.72856053]]
[[0.95600171 0.20768181 0.82844489 0.14928212]
 [0.51280462 0.1359196  0.68903648 0.84174772]
 [0.425509   0.956926   0.82533291 0.33821531]
 [0.57576055 0.75330186 0.82710394 0.93343847]]


In [60]:
#실습
#1
np.zeros((3,4))
np.full((3,4), 5)

#모범 답안
a1 = np.zeros((3,4))
a2 = np.full((3,4), 5)
print(a1, a2, sep="\n")


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#2
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [30]:
#3
np.random.rand(2, 3)

array([[0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985]])

In [64]:
#4 (평균, 표준편차, 개수)
rng3 = default_rng(seed=3)
print(rng3.normal(100,20,6))

#모범 답안
a4 = np.random.normal(100,20,6)
print(a4)

[140.81838243  48.88669937 108.36197693  88.64460788  90.94701416
  95.68805674]
[ 90.8077536  110.69641749 129.38514734  77.93584258 101.96073366
 114.44270696]


In [ ]:
#5
#1부터 20까지의 정수를 포함하는 1차원 배열을 만들고, 이 배열을 (4, 5) 크기의 2차원 배열로 변환
a = np.arange(1,21,1)
a = a.reshape(4,5)
print(a)

#모범답안: 아니 이렇게 한꺼번에 붙여도 되구나?
a5 = np.arange(1,21).reshape(4,5)
print(a5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
#6
#0부터 1까지 균등 간격으로 나눈 12개의 값을 가지는 배열을 생성하고, 이를 (3, 4) 크기로 변환하세요

rng4 = default_rng(seed=2)

print(rng4.random((3,4)))

#모범답안
a6 = np.linspace(0,1,12).reshape(3,4)

[[0.26161213 0.29849114 0.81422574 0.09191594]
 [0.60010053 0.72856053 0.18790107 0.05514663]
 [0.27496937 0.65743301 0.56226566 0.15006226]]


In [ ]:
#7
#0~99 사이의 난수로 이루어진 (10, 10) 배열을 생성한 뒤, 
# np.eye()로 만든 단위 행렬을 더 하여 대각선 요소가 1씩 증가된 배열을 만드세요

#random.randint(low,high,(size))
v = np.random.randint(0, 99, (10,10))
v1 = np.eye(10)

print(v)
print(v + v1)


#모범 답안
a7 = np.random.randint(0,100,(10,10))
a7_1 = np.eye(10,10)
# a7+a7_1 하는게 맞다.

[[ 3 29 16 84 82 14 51 79 17 50]
 [53 25 48 17 32 81 80 41 90 12]
 [30 81 17 16  0 31 73 64 38 22]
 [96 66 67 62 95 27 82 62 77 48]
 [93 75 86 37 11 21 33 95 43 88]
 [96 73 40 43 90 71  8 85 72 28]
 [30 89 25 78 81 85 62 13 41 33]
 [ 4 87 94 28 39 91  9  7 22 32]
 [ 3  9 52 76 68 30 70 74 30  9]
 [ 2 65 13 75 52  5 93 84 48 62]]
[[ 4. 29. 16. 84. 82. 14. 51. 79. 17. 50.]
 [53. 26. 48. 17. 32. 81. 80. 41. 90. 12.]
 [30. 81. 18. 16.  0. 31. 73. 64. 38. 22.]
 [96. 66. 67. 63. 95. 27. 82. 62. 77. 48.]
 [93. 75. 86. 37. 12. 21. 33. 95. 43. 88.]
 [96. 73. 40. 43. 90. 72.  8. 85. 72. 28.]
 [30. 89. 25. 78. 81. 85. 63. 13. 41. 33.]
 [ 4. 87. 94. 28. 39. 91.  9.  8. 22. 32.]
 [ 3.  9. 52. 76. 68. 30. 70. 74. 31.  9.]
 [ 2. 65. 13. 75. 52.  5. 93. 84. 48. 63.]]


In [ ]:
#8
#0~9 사이의 난수로 이루어진 (2, 3, 4) 3차원 배열을 생성하세요

np.random.randint(0, 9, (2,3,4))

#모범답안
a8= np.random.randint(0,10,(2,3,4))

array([[[2, 8, 0, 7],
        [6, 5, 8, 2],
        [2, 0, 1, 2]],

       [[3, 5, 7, 8],
        [7, 7, 6, 2],
        [0, 4, 5, 4]]], dtype=int32)

### 1-5. 인덱싱과 슬라이싱
- 다차원 배열을 다루는 편의 기능 제공
- Python의 시퀸스보다 빠름

In [ ]:
#인덱싱 a[]<인덱싱 좌표
a = np.array([10,20,30,40,50])
print(a[2])
print(a[-1])

30
50


In [68]:
# 다차원 인덱싱
#파이썬 리스트
matrix = [[1,2,4], [4,5,6]]
print("파이썬 인덱싱:",matrix[1][1])

#numpy 배열
a2 = np.array([[1,2,4],[4,5,6]])
print("numpy 인덱싱:", a2[1,1])

#3차원 배열 인덱싱
a3 = np.arange(24).reshape(2,3,4)
print(a3)
print("numpy 인덱싱:", a3[1,1,1])

파이썬 인덱싱: 5
numpy 인덱싱: 5
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
numpy 인덱싱: 17


In [69]:
# 슬라이싱
# arr[행 슬라이스, 열 슬라이스]
# arr[..., 4차원 슬라이스, 3차원 슬라이스, 2차원, 1차원]

a1 = np.array([10,20,30,40,50])
print(a1[1:3])
print(a1[2:])
print(a1[:2])
print(a1[:])
print(a1[::2])
print(a1[::-1])

[20 30]
[30 40 50]
[10 20]
[10 20 30 40 50]
[10 30 50]
[50 40 30 20 10]


In [70]:
# 파이썬 리스트와의 차이
# 파이썬 리스트
py_list = [10,20,30,40,50]
sliced = py_list[1:4]
sliced[1] = 100
print("py 원본",py_list)
print("py 슬라이싱", sliced)
print()

#numpy 배열
a1 = np.array([10,20,30,40,50])
a1_silced = a1[1:4]
a1_silced[1] = 100
print("numpy 원본",a1)
print("numpy 슬라이싱",a1_silced)

py 원본 [10, 20, 30, 40, 50]
py 슬라이싱 [20, 100, 40]

numpy 원본 [ 10  20 100  40  50]
numpy 슬라이싱 [ 20 100  40]


In [71]:
#실습
#1
arr= np.arange(10, 30, 2)
print(arr[[1,3,5]])

[12 16 20]


In [ ]:
#2 3x3 배열에서 왼쪽 위 → 오른쪽 아래 대각선의 요소만 인덱싱으로 추출하세요
arr= np.arange(1, 10).reshape(3, 3)
print(arr[0,0],arr[1,1],arr[2,2])

#모범 답안
#arr[[0,1,2],[0,1,2]]


#3 3x4 배열에서 마지막 열만 선택해 모두 -1로 변경하세요
arr= np.arange(1, 13).reshape(3, 4)
arr[0,3] = -1
arr[1,3] = -1
arr[2,3] = -1

print(arr)

#모범 답안
arr[:,:3] = -1

1 5 9
[[ 1  2  3 -1]
 [ 5  6  7 -1]
 [ 9 10 11 -1]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
#4 4x4 배열에서 행을 역순, 열을 역순으로 각각 슬라이싱해 출력하세요
arr= np.arange(1, 17).reshape(4, 4)
print(arr[::-1])
print(arr[:,::-1])

#모범 답안
print("행 역순", arr[::-1])
print("열 역순", arr[:,::-1]) #열 기준, 뒤에서부터(시작:끝:순서-1)

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [10]:
# 2차원 배열 슬라이싱

a2 = np.arange(1,21).reshape(4,5)
print(a2)

# 행 슬라이싱
#print(a2[0])
#print(a2[1])
#print(a2[1:3])
#print(a2[2:])
print()

#열 슬라이싱
print(a2[:,2])
print(a2[:,-1])
print(a2[:,1:3])
print()

#행과 열의 슬라이싱
print(a2[1:3, 2:4])
print(a2[2:, 3:])
print(a2[::2,::2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[ 3  8 13 18]
[ 5 10 15 20]
[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]

[[ 8  9]
 [13 14]]
[[14 15]
 [19 20]]
[[ 1  3  5]
 [11 13 15]]


In [12]:
# 3 차원 슬라이싱
a3 = np.arange(36).reshape(3,3,4) #정수 지정, 행렬 설정
print(a3)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]


In [ ]:
# 얕은 복사: 복사본이 원본과 메모리를 공유 > 변경 사항이 서로에게 영향을 줌

b1 = np.array([1,2,3])
b1_viewd = b1.view()
b1_viewd[1] = 10
print("원본",b1)
print("복사본", b1_viewd)
print()

# 깊은 복사: 복사본이 원본과 독립적으로 복사됨 > 서로 영향 주지 않는다.

b2 = np.array([1,2,3])
b2_viewd = b2.copy()
b2_viewd[1] = 20
print("원본", b2)
print("복사본", b2_viewd)
print()

In [15]:
# Fancy Indexing
# 정수 배열을 사용하여 여러 인덱스로 여러 요소를 한번에 선택
af = np.arange(1,21)
print(af)
print(af[[4,7,1]])

af2 = np.arange(1,21).reshape(4,5)
print(af2)
print(af2[[1,3],[2,4]])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[5 8 2]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 8 20]


In [18]:
# boolean Indexing
ab = np.linspace(10,100,10)
print(ab)
print(ab[ab>40])
print()

#boolean masking
ab2 = np.arange(0,21)
print(ab2)
mask = ab2 % 2 == 0
print(mask)
print(ab2[mask])

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[ 50.  60.  70.  80.  90. 100.]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True]
[ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
#실습
#5 4x5 배열에서 가운데 2x3 부분을 슬라이싱한 뒤 copy()를 이용해 독립 배열을 만드세요
arr= np.arange(1, 21).reshape(4, 5)
print(arr)

arr_viewd = arr.copy()
arr_viewd = arr[1:3, 1:4]
print("원본", arr)
print("복사본", arr_viewd)

#모범 답안
arr_viewd = arr[1:3,1:4].copy

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
원본 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
복사본 [[ 7  8  9]
 [12 13 14]]


In [ ]:
#6  3x4 배열에서 짝수이면서 10 이상인 값만 선택하세요.(&을활용)

arr= np.array([[ 4,  9, 12,  7], [10, 15, 18,  3], [ 2, 14,  6, 20]])
print(arr[arr>10])

#모범 답안
print(arr[(arr % 2 == 0) & (arr >= 10)])

[12 15 18 14 20]


In [ ]:
#7 5x5 배열에서 2, 4번째 행을 선택하고, 선택된 행에서 열 순서를 [4, 0, 2]로 재배치

arr= np.arange(1, 26).reshape(5, 5)
print(arr)

arr_1 = arr[[1,3]]
print(arr_1[::-1,[4,0,2]])

#모범 답안
arr_1 = arr[[1,3]]
arr_1[:,[4,0,2]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[20 16 18]
 [10  6  8]]


In [ ]:
#8 5x3 배열에서 각 행의 첫 번째 값이 50 이상인 행만 Boolean Indexing으로 선택

arr= np.array([[10, 20, 30], [55, 65, 75], [40, 45, 50], [70, 80, 90], [15, 25, 35]])
arr[arr>50].reshape(2,3)

#모범 답안
arr[arr[: ,0] >= 50 ]

array([[55, 65, 75],
       [70, 80, 90]])

In [ ]:
#9  4x4 배열에서 (0,1), (1,3), (2,0), (3,2) 위치의 요소를 한 번에 선택

arr= np.arange(1, 17).reshape(4, 4)
print(arr)

print(arr[[0,1,2,3],[1,3,0,2]])

#모범 답안
arr[[0,1,2,3],[1,3,0,2]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 2  8  9 15]


In [ ]:
#10 3차원 배열 (2, 3, 4)에서 모든 블록에서 두 번째 열만 추출해 새로운 2차원 배열 (2, 3)을 만드세요

arr3d = np.arange(24).reshape(2, 3, 4)
print(arr3d[:,:,1].reshape(2,3))

#모범 답안
arr3d[:,:,1]

[[ 1  5  9]
 [13 17 21]]


In [71]:
# numpy 실습 종합
#0부터 24까지 정수를 가진 배열을 만들고, (5, 5) 배열로 변환한 뒤
# 가운데 행(3번째 행)과 가운데 열(3번째 열)을 각각 1차원 배열로 출력하세요

a = np.arange(0,25).reshape(5, 5)
print(a)
a1 = a[[2]]
a2 = a[:,3]
print(a1)
print(a2)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[10 11 12 13 14]]
[ 3  8 13 18 23]
a1a2


In [92]:
#0~99 난수로 이루어진 (10, 10) 배열을 생성하고,짝수 인덱스의 행만 선택하여 출력하세요
b = np.random.randint(0,100,(10,10))
print(b)
print(b[::2])


[[84 72 69 70 14 87 15 59 49 83]
 [76 99 23 75 38 88 30 59 79 22]
 [79 40 56 33 72 58  3 74 34 66]
 [60 58 16 41 80 29 54  3  1 96]
 [72 27 88 55 77  4 61 14 36 16]
 [56  0 81 88 71 50 59  6 56 37]
 [55  6 36 45 89 64 64  7 47 22]
 [50 46  7 82 82 57 99 68 55 30]
 [28 43  4 12 99 19 79 22 63  7]
 [56 75 11 67 37 14 39 10 91 59]]
[[84 72 69 70 14 87 15 59 49 83]
 [79 40 56 33 72 58  3 74 34 66]
 [72 27 88 55 77  4 61 14 36 16]
 [55  6 36 45 89 64 64  7 47 22]
 [28 43  4 12 99 19 79 22 63  7]]


In [90]:
#0부터 49까지 정수를 가진 배열을 (5, 10) 배열로 변환한 후, 
# 2행 3열부터 4행 7열까지의 부분 배열을 추출하세요
c = np.arange(0,50).reshape(5,10)
print(c)
print(c[1:4,2:7])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[12 13 14 15 16]
 [22 23 24 25 26]
 [32 33 34 35 36]]


In [ ]:
# 0~9 난수로 이뤄진 (4,4)배열 형성하고 인덱싱으로 추출(for사용)
# 문제 이해가 잘 안 간다...
# 전부 못 풀어서 생략
a4 = np.random.randint(0,10,(4,4))
print(a4)
print(a4[[0,1,2,3],[0,1,2,3]])
print(a4[[0,1,2,3],[3,2,1,0]])


answer = []
answer2 = []
for i in range(4):
    answer.append(a4[i][i])
    answer2.append(a4[i][3 - i]) #인덱스 뒤로 하는 좌표값 지정
print("주대각선:\n",answer)
print("주대각선:\n",answer2)

[[4 7 0 4]
 [4 9 4 7]
 [4 8 3 9]
 [0 6 1 6]]
[4 9 3 6]
[4 4 8 0]
주대각선:
 [np.int32(4), np.int32(9), np.int32(3), np.int32(6)]
주대각선:
 [np.int32(4), np.int32(4), np.int32(8), np.int32(0)]


In [96]:
# 0~9 난수로 이뤄진 (3,4,5) 3차원 배열 생성 
# 2번째 층에서 첫번째 행과 마지막 열 출력

a5 = np.random.randint(0,10,(3,4,5))
print(a5)

print(a5[1, 0,-1])

[[[5 2 7 2 4]
  [4 8 4 1 2]
  [1 7 0 5 6]
  [7 7 7 6 2]]

 [[6 5 5 1 5]
  [9 2 6 5 0]
  [3 5 6 2 7]
  [6 3 0 7 1]]

 [[1 0 3 8 3]
  [7 2 8 9 5]
  [1 6 5 7 1]
  [0 2 4 7 0]]]
5


In [ ]:
# 35부터 74까지 1차원 배열 생성

a6 = np.arange(35,75).reshape(10,4)
#맨 끝의 행부터 역순 출력
a7 = a6[1:-1,2:]
print(a7)
#두번째 행부터 마지막 직전 행, 세번째 열부터 마지막 열까지
#못 풀음
#a8 = a6[1:-1,2:]
#print(a8)

[[41 42]
 [45 46]
 [49 50]
 [53 54]
 [57 58]
 [61 62]
 [65 66]
 [69 70]]
[[41 42]
 [45 46]
 [49 50]
 [53 54]
 [57 58]
 [61 62]
 [65 66]
 [69 70]]


In [110]:
#9 1부터 50까지의 정수 난수로 된 5x6 배열 만들고 배열에서 짝수만 선택하여 출력
arr = np.random.randint(1, 51,(5,6))
print(arr[arr % 2 ==0])


[36  8 10 42  8  6 10 32 16  8 10 50 46 10]


In [ ]:
#10
arr = np.arange(100).reshape(10,10)

#seleted_row = arr[[1,3,5]]

a10 = arr[[1,3,5]][:, [2,4,6]] #1,3,5 번째 행과 2,4,6열 교차하는 원소
print(a10)

[[12 14 16]
 [32 34 36]
 [52 54 56]]


In [109]:
#11
arr = np.random.randint(0,10,15)
idx_2 = arr[::2]
print(idx_2)
idx_3 = idx_2[idx_2 >=5]
print(idx_3)

[6 2 3 7 9 6 7 9]
[6 7 9 6 7 9]
