## 02. numpy

### 2-1. 넘파일 배열 연산

In [2]:
import numpy as np

In [3]:
# 배열 간 연산(1차원)

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(a1 + a2)
print(a1 - a2)

[5 7 9]
[-3 -3 -3]


In [5]:
# 배열 간 연산 (2차원)

a1 = np.arange(1,5).reshape(2,2)
a2 = np.arange(11,15).reshape(2,2)

print(a1)
print(a2)
print(a1 + a2)
print(a1 - a2)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
[[12 14]
 [16 18]]
[[-10 -10]
 [-10 -10]]


In [6]:
# 배열과 스칼라 연산(1차원)
a1 = np.array([1,2,3,4])
print(a1 + 10)
print(a1 * 2)

[11 12 13 14]
[2 4 6 8]


In [7]:
# 배열과 스칼라 연산 (2차원)
a1 = np.arange(1,5).reshape(2,2)
a2 = np.arange(11,15).reshape(2,2)

print(a1)
print(a2)
print(a1 + 5)
print(a2 * 3)
print(a2 / 2)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
[[6 7]
 [8 9]]
[[33 36]
 [39 42]]
[[5.5 6. ]
 [6.5 7. ]]


In [9]:
# 배열의 구조가 다를 경우
a1 = np.array([1,2])
a2 = np.array([1,2,3])
#print(a1 + a2) #ValueError

In [11]:
# 브로드캐스팅
#자동으로 배열의 크기를 확장 > 서로 다른 크기의 배열 간 연산을 가능하게 하는 기능
# 1 두 배열의 차원은 뒤(낮은 차원)에서부터 비교
# 2 크기가 같거나
# 3 한 쪽이 1인 경우 확장 가능

a1 = np.array([[1,2,3],
              [4,5,6]]) # (2,3) 배열
a2 = np.array([10,20,30]) #길이가 3인 1차원 배열 (3,)

# 1차원 길이 3 
[10,20,30]
# 2차원으로 변형 (1,3)
[[10,20,30]]

#2차원 행이 2 -> 2로 확장
[[10,20,30],
 [10,20,30]]

print(a1 + a2)

[[11 22 33]
 [14 25 36]]


In [ ]:
#브로드캐스팅 예제

a1 = np.array([[1],[2],[3]]) #(3,1)
a2 = np.array([10,20,30]) #(3,)

#a2 = (3,) > (1,3)변형 : 한줄 자리를 3줄로 바꿔야 하니까
[[10,20,30]]
#a1 과 a2 비교 > (3,1), (1,3)
[[1,1,1],[2,2,2],[3,3,3]]
[[10,20,30],[10,20,30],[10,20,30]]

print(a1+a2)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [16]:
#실습
#다음 배열을 생성하고, 모든 요소에 3을 더하세요
arr = np.array([1, 2, 3, 4])
print(arr + 3)

#아래 2차원 배열에서 각요소를 -1로 곱한 새로운 배열을 만드세요
arr = np.array([[5, 10],
                [15, 20]])
arr_1 = arr * -1
print(arr_1)

#아래 두 배열의 요소별 곱셈과 나눗셈 결과를 각각 출력하세요
arr1 = np.array([2, 4, 6])
arr2 = np.array([1, 2, 3])

print(arr1 / arr2)
print(arr1 * arr2)

[4 5 6 7]
[[ -5 -10]
 [-15 -20]]
[2. 2. 2.]
[ 2  8 18]
