## 03. Numpy
### 3-1. 배열의 형태 변형과 차원 확장/축소

In [1]:
import numpy as np

In [3]:
# array.ravel()
# 다차원 배열을 1차원 배열로 펼침
# 결과를 view로 반환( view 변경시, 원본도 변경)

a = np.array([[1,2,3],[4,5,6]])
print(a)

flat = a.ravel()
print(flat)

flat[2] = 100
print(flat)
print(a)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[  1   2 100   4   5   6]
[[  1   2 100]
 [  4   5   6]]


In [6]:
# array.flatten()
# 다차원 배열을 1차원 배열로 펼침
# 결과를 복사본으로 반환 (복사본 변경 시, 원본은 변경되지 않는다.)
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)

flat = a.flatten()
print(flat)

flat[4]=0
print(flat)
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]
[1 2 3 4 0 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [35]:
# np.expand_dims(a, axis)
# 지정한 위치에 차원 추가 (차원 확장)
# 추가되는 차원은 1
a = np.array([[1,2,3], [4,5,6]])
print("원본:", a.shape)

# axis = 0
a0 = np.expand_dims(a, axis=0)
print("a0", a0.shape)
print("a0", a0)

# axis = 1
a1 = np.expand_dims(a, axis=1)
print("a1", a1.shape)
print("a1", a1)

# axis = 2
a2 = np.expand_dims(a, axis=2)
print("a2", a2.shape)
print("a2", a2)

원본: (2, 3)
a0 (1, 2, 3)
a0 [[[1 2 3]
  [4 5 6]]]
a1 (2, 1, 3)
a1 [[[1 2 3]]

 [[4 5 6]]]
a2 (2, 3, 1)
a2 [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [36]:
# np.squeeze(a, axis)
# - 배열에서 크기가 1인 차원을 제거해주는 함수 (차원 축소)
a = np.array([[[[1],[2],[3]]], [[[1],[2],[3]]]])
print(a.shape) # (2, 1, 3, 1)

s = np.squeeze(a)
print(s)
print(s.shape)


(2, 1, 3, 1)
[[1 2 3]
 [1 2 3]]
(2, 3)


In [29]:
# axis 지정하는 경우
a2 = np.zeros((1,4,1,2))
print(a2.shape)

s1 = np.squeeze(a2, axis=0)
print(s1.shape)

s2 = np.squeeze(a2, axis=2)
print(s2.shape)

#차원의 크기가 1이 아닌 차원은 제거할 수 X
#s3 = np.squeeze(a2, axis=1) #ValueError

(1, 4, 1, 2)
(4, 1, 2)
(1, 4, 2)


In [33]:
#np. unique()
# 배열에서 중복된 요소를 제거
a = np.array([1,1,1, 5,5, 2,2,2,2, 4,4,4, 3,3,3])
u1 = np.unique(a) # 고유값의 오름차순 배열 반환 [1 2 3 4 5]
print(u1)

u2, idx, inv, cnt = np.unique(a, return_index=True, return_inverse=True, return_counts=True)
print("인덱스",idx)
print("원본의 고유값 인덱스",inv)
print("값의 등장 횟수",cnt)

[1 2 3 4 5]
인덱스 [ 0  5 12  9  3]
원본의 고유값 인덱스 [0 0 0 4 4 1 1 1 1 3 3 3 2 2 2]
값의 등장 횟수 [3 4 3 3 2]


In [50]:
# 실습
#ravel 과 flatten을 각각 사용해 1차원 배열로 변환
#arr의 첫번째 원소(arr[0,0])를 999로 바꾼 뒤 ravel 결과와 flatten 결과에 어떤 변화가 있는지 확인
arr = np.array([[10, 20], [30, 40], [50, 60]])

flat1 = arr.ravel()
flat1[0] = 999
print("ravel 적용\n",flat1)
print(arr)

arr = np.array([[10, 20], [30, 40], [50, 60]])
flat2 = arr.flatten()
flat2[0]=999
print("flatten 적용\n", flat2)
print(arr)


#크기가32x32인 이미지 데이터를 가정하고, 이 배열에 대해 expand_dims를 사용하여
#shape (1, 32, 32)로 바꾸는 코드를 작성
img= np.random.rand(32, 32)

# axis = 0
img1 = np.expand_dims(img, axis=0)
print("img1 차원\n", img1.shape)

ravel 적용
 [999  20  30  40  50  60]
[[999  20]
 [ 30  40]
 [ 50  60]]
flatten 적용
 [999  20  30  40  50  60]
[[10 20]
 [30 40]
 [50 60]]
img1 차원
 (1, 32, 32)


In [ ]:
#아래 배열에서 불필요한 1차원을 모두 제거하여 shape이(28, 28)이 되도록 만드세요
img= np.random.randint(0, 255, (1, 28, 28, 1)) #차원 축소라는 뜻 같다. 

img_p = np.squeeze(img) # 1차원 전부를 없애줌.
print(img_p.shape)

#아래2차원 배열을 1) 1차원 배열로 만든 후2) 중복값을 제거한 뒤 shape (1, n)으로 재구성
arr = np.array([[3, 1, 2, 2],
                [1, 2, 3, 1],
                [2, 2, 1, 4]])

arr_1 = np.squeeze(arr) #arr_1 = np.flatten(arr)
arr_2 = np.unique(arr_1)
print(arr_2.shape)
arr_3 = np.array(arr_2).reshape(1,4)
print(arr_3)


(28, 28)
(4,)
[[1 2 3 4]]


In [ ]:
#다음 배열을 shape (10,)로 만든 뒤 고유값 배열을 구하세요
arr = np.array([[[1], [3], [2], [1], [3], [2], [3], [1], [2], [3]]]) # shape ( 1, 10, 1)

arr1 = arr.reshape(10)
print(arr1)
#arr1 = np.squeeze(arr) 이걸 써야 했던 거다...(ㅎ)
#arr2 = np.unique(arr1) 고유값 배열 만들기.

#다음 배열을 1차원 배열로 만든 후 고유값만 추출해서shape (고유값개수, 1)인2차원 배열로 변환하세요
arr = np.array([ [[0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5]],
                [[3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8]] ]) # shape ( 2, 3, 4)

flat1 = arr.flatten()
print("flatten 적용\n", flat1)
u1 = np.unique(flat1)
print(u1)
u2 = u1.reshape(9,1) #u2 = np.expand_dims(u1, axis=1) 사용
print(u2)

[1 3 2 1 3 2 3 1 2 3]
flatten 적용
 [0 1 2 3 1 2 3 4 2 3 4 5 3 4 5 6 4 5 6 7 5 6 7 8]
[0 1 2 3 4 5 6 7 8]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


### 3-2. 배열의 결합과 분리

In [ ]:
#np. concatenate()
#배열 시퀀스를 결합
#기존 구조 안에서 결합
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

result1 = np.concatenate((a,b), axis=0)
print(result1)
print(result1.shape) #(3,2) 3행(가로3) 2열(세로2)

#결합 불가 > 결합하는 axis를 제외한 나머지 차원이 같아야 함.
#result2 = np.concatenate((a,b),axis=1) #ValueError

c = np.array([[7],[8],[9]])
result3 = np.concatenate((result1,c), axis=1)
print(result3)
print(result3.shape) #(3,3) 7 8 9가 행에 하나씩 추가되어 3열 됨. 

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2 7]
 [3 4 8]
 [5 6 9]]
(3, 3)


In [ ]:
# np.stack()
# 새로운 차원을 추가하면서 결합
a = np.array([1,2,3])
b = np.array([4,5,6])

# axis = 0
s1 = np.stack((a,b), axis= 0)
print(s1)
print(s1.shape) #(2,3)

#axis = 1
s2 = np.stack((a,b), axis= 1)
print(s2)
print(s2.shape) #(3,2) 열(세로) 형태로 만들어 합침

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [ ]:
#hstack()
# 열 방향(가로)로 결합
a = np.array([1,2,3])
b = np.array([4,5,6])

h = np.hstack((a,b))
print(h) #[1 2 3 4 5 6]

#vstack() - 행 방향(세로)로 결합
h1 = np.vstack((a,b))
print(h1)
#[[1 2 3]
#[4 5 6]]

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [76]:
# np.split()
# 배열을 여러개의 하위 배열로 분할
a = np.arange(9)
s = np.split(a, 3)

print(a)
print(s)
print(s[0])
print(s[1])
print(s[2])

#s2 = np.split(a, 4) 
#ValueError: array split does not result in an equal division (균일하게 나눌 수 없다.)



[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[0 1 2]
[3 4 5]
[6 7 8]


In [79]:
a = np.arange(16).reshape(4,4)
print(a)

s1 = np.split(a,[1,3])
print(s1)
for part in s1:
    print(part)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]
[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [ ]:
#실습
#다음 두 배열을 행방향으로 이어붙이세요
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

ab = np.vstack((a,b))
print(ab)
# 모범 답안 print(np.concatenate((a,b)))

#아래 배열을 3개로 같은 크기로 분할하세요.
a = np.arange(12)
a1 = np.split(a, 3)
print(a1)
#a1 = np.split(a, 3)
#for part in a1:
#    print(part)

#다음 배열들을 새로운 축에 쌓아 shape이(3, 2)인 배열을 만드세요
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

abc = np.stack((a,b,c),axis=0) #행 기준으로 
print(abc)
print(abc.shape) #[]가 3행 세로로 늘어진게 열인가 보다(헷갈려)

[[1 2]
 [3 4]
 [5 6]]
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [ ]:
#shape가(2, 3)인 아래 두배열을shape (2, 2, 3)인 3차원 배열을 만드세요.
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

ab = np.stack((a,b), axis= 1)
print(ab)
print(ab.shape)
#axis = 0하면 (2<,2,3)에 2<부분이 추가됨.

#아래의 1차원 배열을 2:3:3 비율(총3개)로 분할하세요
arr = np.arange(8)

arr1 = np.split(arr,(2,5))
print(arr1)


#아래 두배열을axis=0, axis=1로 각각 stack하여 두경우의 결과shape을 모두 구하세요
a = np.ones((2, 3))
b = np.zeros((2, 3))

h1 = np.stack((a,b),axis=0)
print(h1.shape)
h2 = np.stack((a,b),axis=1)
print(h2.shape)


[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
(2, 2, 3)
[array([0, 1]), array([2, 3, 4]), array([5, 6, 7])]
(2, 2, 3)
(2, 2, 3)


### 3-3 배열의 정렬

In [ ]:
#np.sort(array)
#정렬된 복사본 반환
#array.sort()
#원본 배열을 정렬

#1차원 배열
a = np.array([3,1,4,2])

#정렬한 배열을 반환
s = np.sort(a)
print(a) #원본 요소는 그대로 위치함. 정렬된 복사본이 생기는 거라.
print(s) 

#원본을 정렬
a.sort()
print(a)

#내림차순: sort한 후 배열 뒤집어야 함.
print(a[::-1]) #인덱스 -1로 뒤로 나오게 출력

[3 1 4 2]
[1 2 3 4]
[1 2 3 4]
[4 3 2 1]


In [ ]:
# 2차원 배열 정렬
a = [[6,5,4], [3,2,1]]
s1 = np.sort(a, axis=0) #열 안에서 열끼리 정렬 (세로)
print(s1)
s2 = np.sort(a, axis=1) #행 기준으로 정렬(가로)
print(s2)

[[3 2 1]
 [6 5 4]]
[[4 5 6]
 [1 2 3]]


In [106]:
# np.argsort()
# 정렬 인덱스를 반환

a = np.array([3,5,1,2,4])
idx = np.argsort(a)
print(idx)
print(a[idx])

[2 3 0 4 1]
[1 2 3 4 5]


In [109]:
#실습
#아래의 1차원 배열을 오름차순과 내림차순으로 각각 정렬하는 코드를 작성하세요
arr = np.array([7, 2, 9, 4, 5])
s = np.sort(arr)
print(s)
print(s[::-1])

#아래의 2차원 배열에서 각행(row) 별로 오름차순 정렬된 배열을 구하세요
arr = np.array([[9, 2, 5],
                [3, 8, 1]])
a1 = np.sort(arr, axis=1) #행 기준으로 정렬(가로)
print(a1)


[2 4 5 7 9]
[9 7 5 4 2]
[[2 5 9]
 [1 3 8]]


In [111]:
#아래의1차원 배열에서 정렬결과(오름차순)가 되는 인덱스 배열을 구하고, 
#그 인덱스를 이용해 원본배열을 직접 재정렬하는 코드를 작성하세요
arr = np.array([10, 3, 7, 1, 9])

idx = np.argsort(arr) #정렬 인덱스 반환
print(idx) #인덱스
print(arr[idx])

#아래2차원 배열을 열(column) 기준(axis=0)으로 오름차순 정렬된배열을 구하세요
arr = np.array([[4, 7, 2],
                [9, 1, 5],
                [6, 8, 3]])

s1 = np.sort(arr, axis=0)
s2 = np.sort(s1)
print(s1)
print(s2)


[3 1 2 4 0]
[ 1  3  7  9 10]
[[4 1 2]
 [6 7 3]
 [9 8 5]]
[[1 2 4]
 [3 6 7]
 [5 8 9]]
