# 03. 텐서의 조작

# 3-1 인덱싱, 슬라이싱
- numpy와 동일한 방식으로 인덱싱, 슬라이싱 가능

In [1]:
import torch

In [5]:
x = torch.tensor([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

# 행 -> 열 순서로 진행
print(x[1,1]) #5
print(x[2,0]) #7
print(x[0, :]) # 0행 전체
print(x[:,2]) # 2열 전체
print(x[[0,1,2], [0,1,2]]) # fancy 인덱싱
print(x[x > 5]) # boolean 인덱싱

tensor(5)
tensor(7)
tensor([1, 2, 3])
tensor([3, 6, 9])
tensor([1, 5, 9])
tensor([6, 7, 8, 9])


In [7]:
x = torch.tensor([10,20,30,40,50])

x[0] = 100
print(x)

# 슬라이싱으로 값을 변경할 시 tensor로 값을 할당
x[1:4] = torch.tensor([200,300,400])
print(x)

tensor([100,  20,  30,  40,  50])
tensor([100, 200, 300, 400,  50])


### 3-2 텐서의 크기, 모양 변경
- torch.view()

In [4]:
x = torch.randn(4, 5)
print(x)
y = x.view(20)
print(y)
z = y.view(5, -1) # -1 > 자동계산
print(z)

n = z.view(2, 2, 5)
print(n)

tensor([[ 1.4115, -1.2178,  0.0083,  0.3313, -1.4923],
        [-1.5502, -0.6279, -1.7072,  0.1570,  0.6013],
        [ 1.8745, -0.7284,  1.2888,  0.7172,  0.4077],
        [ 0.6095,  0.2865, -0.5519, -0.1788,  1.4098]])
tensor([ 1.4115, -1.2178,  0.0083,  0.3313, -1.4923, -1.5502, -0.6279, -1.7072,
         0.1570,  0.6013,  1.8745, -0.7284,  1.2888,  0.7172,  0.4077,  0.6095,
         0.2865, -0.5519, -0.1788,  1.4098])
tensor([[ 1.4115, -1.2178,  0.0083,  0.3313],
        [-1.4923, -1.5502, -0.6279, -1.7072],
        [ 0.1570,  0.6013,  1.8745, -0.7284],
        [ 1.2888,  0.7172,  0.4077,  0.6095],
        [ 0.2865, -0.5519, -0.1788,  1.4098]])
tensor([[[ 1.4115, -1.2178,  0.0083,  0.3313, -1.4923],
         [-1.5502, -0.6279, -1.7072,  0.1570,  0.6013]],

        [[ 1.8745, -0.7284,  1.2888,  0.7172,  0.4077],
         [ 0.6095,  0.2865, -0.5519, -0.1788,  1.4098]]])


### 3-3. 텐서의 숫자값 얻기
-tensor.item(): 스칼라 값 하나만 존재해야 사용 가능

In [6]:
x = torch.rand(2)
print(x)
print(x[0])

print(x[0].item())

tensor([0.6906, 0.4391])
tensor(0.6906)
0.6905500888824463


### 3-4. 차원 축소 및 증가
#### 차원 축소(제거)
- torch.squeeze(): 크기가 1인 차원을 제거함

In [9]:
t = torch.rand(3,1,3)
print(t)
print(t.shape)

ts = torch.squeeze(t)
print(ts)
print(ts.shape)

tensor([[[0.5957, 0.8786, 0.7473]],

        [[0.5211, 0.0998, 0.7150]],

        [[0.2656, 0.6375, 0.4418]]])
torch.Size([3, 1, 3])
tensor([[0.5957, 0.8786, 0.7473],
        [0.5211, 0.0998, 0.7150],
        [0.2656, 0.6375, 0.4418]])
torch.Size([3, 3])


#### 차원 증가(생성)
- torch.unsqueeze(): dim 설정에 따라 차원을 증가시킴
- dim은 하나의 차원이 추가되는 인덱스

In [ ]:
t = torch.rand(3,3,3)
print(t.shape)

# 0 가장 상위 차원 - > 3 가장 하위 차원
ts1 = torch.unsqueeze(t, dim=0)
print(ts1.shape)

ts2 = torch.unsqueeze(t, dim=1)
print(ts2.shape)

ts3 = torch.unsqueeze(t, dim=2)
print(ts3.shape)

ts4 = torch.unsqueeze(t, dim=3) #없는 위치에도 생성 가능
print(ts4.shape)

torch.Size([3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([3, 1, 3, 3])
torch.Size([3, 3, 1, 3])
torch.Size([3, 3, 3, 1])


### 3-5. 텐서간 결합
- torch.stack(): 동일한 형식의 텐서를 새롭게 그룹화 함 -> 새로운 차원 생성됨.

In [15]:
x = torch.tensor([1,4])
y = torch.tensor([2,5])
z = torch.tensor([3,6])

result = torch.stack([x,y,z])
print(result)
print(result.shape)

a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])

result2 = torch.stack([a,b])
print(result2)
print(result2.shape)

tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([3, 2])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])


- torch.cat(): 데이터를 하나의 텐서로 병합 -> 새로운 차원 생성 X

In [17]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[7,8],[9,10]])

result = torch.cat((a,b), dim=1)
print(result)

# 각각 1번째 2번째 끼리 병합한다.

tensor([[ 1,  2,  7,  8],
        [ 3,  4,  9, 10]])


### 3-6 텐서 나누기
- torch.chunk(): 텐서를 지정한 개수에 따라 나눔
- 나누어 떨어지지 않는 경우 -> 마지막 조각의 크기가 달라짐
- torch.split(): 지정한 사이즈에 따라 나눔
- 나누어 떨어지지 않는 경우 -> 마지막 조각의 크기가 달라짐

In [20]:
t = torch.rand(3,7)
print(t)

t1,t2,t3 = torch.chunk(t, 3, dim=1) #3개씩 나누고, 마지막은 하나만 남아 t3은 1개다.
print(t1)
print(t2)
print(t3)

tensor([[0.5153, 0.2197, 0.9642, 0.6699, 0.3100, 0.9769, 0.5120],
        [0.3643, 0.9852, 0.8085, 0.4832, 0.2256, 0.9792, 0.3161],
        [0.6213, 0.1574, 0.0648, 0.4255, 0.0032, 0.3145, 0.9894]])
tensor([[0.5153, 0.2197, 0.9642],
        [0.3643, 0.9852, 0.8085],
        [0.6213, 0.1574, 0.0648]])
tensor([[0.6699, 0.3100, 0.9769],
        [0.4832, 0.2256, 0.9792],
        [0.4255, 0.0032, 0.3145]])
tensor([[0.5120],
        [0.3161],
        [0.9894]])


In [21]:
t = torch.rand(3,7)
print(t)

# 쪼갤 열의 개수 지정
t1, t2, t3 = torch.split(t, [2,3,2], dim= 1)
print(t1)
print(t2)
print(t3)

tensor([[0.5446, 0.4187, 0.0410, 0.2336, 0.6030, 0.3378, 0.7925],
        [0.3152, 0.2711, 0.6926, 0.8534, 0.2667, 0.6531, 0.1410],
        [0.4621, 0.9559, 0.8057, 0.3917, 0.3465, 0.4751, 0.8079]])
tensor([[0.5446, 0.4187],
        [0.3152, 0.2711],
        [0.4621, 0.9559]])
tensor([[0.0410, 0.2336, 0.6030],
        [0.6926, 0.8534, 0.2667],
        [0.8057, 0.3917, 0.3465]])
tensor([[0.3378, 0.7925],
        [0.6531, 0.1410],
        [0.4751, 0.8079]])
